### ISSUE TITLE
Ubuntu 16.X SWIG bug

### ISSUE THREAD

**Issue by XavierTolza** [CBrunsch/BinViz#2]
On some versions of ubuntu the module does not compile correctly, cmake outputs a warning not stopping the compilation but resulting in a non working OOT module
> ===== cmake output fragment =========
> -- Checking for module SWIG
> -- Disabling SWIG because version check failed.
> ===== fragment end ==================================

When running the module the terminal runs into the following error:
`AttributeError: 'module' object has no attribute 'vizsink_b'`
The solution found on [this bug report](https://github.com/daniestevez/gr-outernet/issues/1) is to install the latest version of SWIG:
`sudo apt install swig swig3.0`
It fixed the bug for me, perhaps you could add it to the readme known bugs section?

**Comment by CBrunsch** [comment]
Thanks! Added a hint to the README.
